---
title: "R Notebook"
output:
---

```{r}
library(httr)
library(jsonlite)
library(dplyr)
library(tidyverse)
library(ggimage)
library(png)
library(RCurl)
library(httr)
library(jsonlite)
library(dplyr)
library(tidyverse)
library(shiny)
library(ggplot2)
library(plotly)
library(bslib)
```

```{r}
charcode <- 2:127
characters <- as.character(charcode)
```

```{r}
res = GET(paste0("https://api-mobilelegends.vercel.app/api/","hero-detail/","1"))
data <- fromJSON(rawToChar(res$content))
s <- data$data$records$data$hero$data
s
```

```{r}
for (chr in charcode){
res = GET(paste0("https://api-mobilelegends.vercel.app/api/","hero-detail/",chr))
data <- fromJSON(rawToChar(res$content))
s2 <- data$data$records$data$hero$data
s <- s|>add_row(s2)
}
head(s)
```

```{r}
write_json(s,"data.json")
```

```{r}
s2 <- fromJSON("data.json")
head((s2))
```

obtaining game statistics

```{r}
res=GET("https://api-mobilelegends.vercel.app/api/hero-rank/?days=7&rank=mythic&size=126&index=1&sort_field=win_rate&sort_order=desc")
```

```{r}
data <- fromJSON(rawToChar(res$content))
s <- data$data$records$data
s <- s|>select(main_heroid,main_hero_appearance_rate,main_hero_ban_rate,main_hero_win_rate)
head(s)
```

```{r}
s2 <- left_join(s2,s, by=c("heroid"="main_heroid"))
head(s2)
```

```{r}
s4 <- s2|>
  select(heroid,name,difficulty,roadsortlabel,sortlabel,speciality,main_hero_appearance_rate,main_hero_ban_rate,main_hero_win_rate,story,sorticon1,sorticon2,roadsorticon1,roadsorticon2,smallmap,head)
head(s4)
```

```{r}
s4 <- s4|>separate(col = sortlabel,c("remove","Role1","Role2"))|>
  select(!remove)|>
  separate(col = speciality,c("remove","Spec1","Spec2"))|>
  select(!remove)|>
  separate(col = roadsortlabel,c("remove","Lane1","Lane2"))|>
  select(!remove)
s4 <- s4|>arrange(desc(main_hero_win_rate))|>
  mutate(rank=as.numeric(rownames(s4)))
s4 <- s4|>select(rank,everything())
```

```{r}
s4
```

```{r}
heroes <- (df|>select(name))[[1]]
t <- df|>filter(rank==which(heroes == "Lolita"))
t
```

```{r}
s4|>ggplot(aes(x = name,y=main_hero_win_rate,color=Role1))+
  geom_point()+
   geom_point(data = t,aes(x = t$name,y=t$main_hero_win_rate),color="gold")+
  theme(axis.text.x=element_blank(), 
      axis.ticks.x=element_blank()) +
  xlab("Heroes")+
  ylab("Win Rate")
 
```

```{r}
img <- readPNG(getURLContent(t$head))
hero_plot_chart <- df|>
      ggplot(aes(x = name,y=main_hero_win_rate,color=Role1))+
      geom_point()+
  geom_point(data = t,aes(x = name,y=main_hero_win_rate),color="gold")+
      theme(axis.text.x=element_blank(), 
            axis.ticks.x=element_blank()) +
      xlab("Heroes")+
      ylab("Win Rate")
      scale_fill_brewer(palette="Dark2")
        
    
    ggplotly(hero_plot_chart, tooltip = "name") 
```

```{r}
hero_ranks <- df|>
      ggplot(aes(x = name,y=rank))+
      geom_bar(stat = "identity",fill="gold")+
      geom_bar(data=t,stat = "identity",fill="red")+
      theme_minimal()+
      theme(axis.text.x=element_blank(), 
            axis.ticks.x=element_blank()) +
      xlab("Heroes")+
      ylab("Win Rate")
    scale_fill_brewer(palette="Dark2")
    ggplotly(hero_ranks, tooltip = c("name","rank"))
```

```{r}
hero_plot_chart <- df|>
      ggplot(aes(x = name,y=rank))+
  geom_bar(stat = "identity",fill="gold")+
  theme_minimal()+
theme(axis.text.x=element_blank(), 
            axis.ticks.x=element_blank()) +
      xlab("Heroes")+
      ylab("Win Rate")
      scale_fill_brewer(palette="Dark2")
        
    
    ggplotly(hero_plot_chart, tooltip = "name") 
```

```{r}
write_json(s4,"data.json")
```

```{r}
df <- fromJSON("src/data.json")
```
